version: '5'
services:
  db:
    container_name: db
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=matin
      - POSTGRES_PASSWORD=matin
      - POSTGRES_DB=postgres
    restart: always             
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo17:
    container_name: odoo
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072" 
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=matin
      - PASSWORD=matin
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
  nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email matin.jamali0023@gmail.com -d certbot.com --agree-tos
    depends_on:
     - odoo17
