version: '3.8'

services:
  odoo:
    image: odoo:17.0 
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=strongpassword  
      - POSTGRES_DB=postgres
    ports:
      - "8069:8069"   
    volumes:
      - odoo-web-data:/var/lib/odoo   
      - ./addons:/mnt/extra-addons   
      - ./config:/etc/odoo   
  db:
    image: postgres:15  
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data   
  nginx:
    image: nginxÿß
    depends_on:
      - odoo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
    ports:
      - "80:80"
      - "443:443"
    networks:
      - odoo-net
    restart: unless-stopped
volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo-net:
